[Home] Add image background shadow gradient effects
DevOli/Marvel-chars pull request #23
Opened 2021-12-13 18:51 UTC by jplozadach

- Colored background shadow gradient to the images in Home and Characters screen added.
- Default perfomance test of side menu view model deleted.

2021-12-13 19:01 UTC, Fernando-Guerrero-jala approved these changes

2021-12-13 19:39 UTC, jmacboy requested changes

2021-12-13 19:39 UTC, jmacboy commented on MarvelCharsApp/MarvelCharsApp/Helpers/UIImageHelper.swift
> +    return UIColor(red: CGFloat(bitmap[0]) / 255, green: CGFloat(bitmap[1]) / 255, blue: CGFloat(bitmap[2]) / 255, alpha: CGFloat(bitmap[3]) / 255)
you're always assuming here that the bitmap has at least 1 row.
Please validate this bitmap length with a default color

2021-12-14 14:35 UTC, jmacboy approved these changes

2021-12-14 16:32 UTC, merged